### ISSUE TITLE
Noteworthy/Feature module

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#11]
Create a module to provide a Noteworthy/Feature content fragment type (implmented as a custom block type or paragraph or ECK).

The Noteworthy/Feature content fragment type is essentially a way of providing teasers of other content. The specific presentation may vary depending on where it is implemented, but is generally going to be more in the style of a visual call out rather than looking like the rest of the text on a page.

In D7, these are currently implemented more as their own content types with discrete fields rather than as a reference to other content.

### Fields
- [ ] Title? Or pull from related content?
- [ ] Sub-title? Or pull from related content?
- [ ] External link
- [ ] Content reference
- [ ] Image? Or pull the image from the related content?
- [ ] Date/time?

**Comment by bspeare** [comment]
@pyrello I'd like to set this up as a custom block using https://uiowa.github.io/hds/components/detail/news-block--default.html and https://uiowa.github.io/hds/components/detail/feature-block--default.html as the presentation base and use custom fields.

**Comment by bspeare** [comment]
The custom fields:

- Title
- Sub-title
- Excerpt
- External link
- Image
- Date/time
- Card Type
  - Hover Block
  - Card

**Comment by pyrello** [comment]
I believe the work you have done on this is being committed via #91
