### ISSUE TITLE
Add a Deadline type to entity_types module.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa01#122]
Add a new submodule to the entity_types module that handles deadlines. Include the following fields: Title, Date, Location, Link, and Description. Create a default view page and block for display.

**Comment by mark-bennett-uiowa** [comment]
I have been playing with adding iCal links to individual and full group .ics files for all upcoming deadlines, events and seminars. Since date_ical hasnt been ported to D8 yet, and views_ical is still in an alpha (and not-working based on my testing) version, this will be added at a later time with a stable views_ical module.

**Comment by pyrello** [comment]
I'm closing this, since it is complete. There is an outstanding issue that is referenced above.
