### ISSUE TITLE
How to handle embedding responsive images?

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#126]
Currently, when images are placed via the media embed button, they are output as `<img>` and not `<picture>` elements. How do we get the same behavior from embedded images that we have built into our image fields?

**Comment by bspeare** [comment]
Good question.  Should we create a separate issue to get the media library working with CKEditor in collegiate_basic before we tackle this issue? https://www.drupal.org/project/drupal/issues/2801307.  It looks like that might be out in 8.8 (10/15/19).

**Comment by pyrello** [comment]
Postponing this until after the release of 8.8, so we can see what pieces of this are resolved by that release.

**Comment by pyrello** [comment]
This is related to #221.

I have tested this against the new 8.8.x release and since the media embed filter supports setting the view mode, this can be done by configuring a view mode to use responsive image styles, then selecting only those view modes for embedded media.

**Comment by pyrello** [comment]
This is fixed with #260
