### ISSUE TITLE
Set layout builder defaults for basic page content type in collegiate_basic

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa01#129]
- Remove page title, breadcrumbs from block display
- Add page title and breadcrumbs as default blocks within the basic page layout
- Limit allowed layouts to collegiate_theme layouts

**Comment by pyrello** [comment]
It looks like this issue is resolved except for the last bullet: Limit allowed layouts to collegiate_theme layouts.

@bspeare Can you provide a little more context for that item?

**Comment by bspeare** [comment]
I was wondering if we could limit the layouts used to only the collegiate_theme layouts since they will be inheriting the theme settings.   For instance, if we allowed each content type to use the core 3-column layout, then a lot of the theme and HDS styling would not be implemented.
