### ISSUE TITLE
Add a section heading component for uiowa_lb_blocks

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa01#136]
- For accessibility, each layout section will need a heading tag that can either be displayed or visually hidden for screen readers. 
- The upcoming 8.8 release brings section headings that might be useful for this: https://www.drupal.org/project/drupal/issues/3073872.
- Layout Builder Styles options will be needed for each heading component.
  - Style, Padding, Margin, and Alignment
- For example, https://uiowa.github.io/hds/components/detail/bold-headline.html would be one option.

**Comment by pyrello** [comment]
Is it intended that when using a block type like UIowa Feature and you select a different heading (e.g. h2, h3, etc.) that they should render at the same size regardless?

**Comment by bspeare** [comment]
I think it depends on if it is a stylized heading or a general heading.   What would you prefer?

**Comment by pyrello** [comment]
I guess I wonder if it's confusing to have the size not change? But if the block type depends on a particular size of heading, then I guess maybe it makes sense. I'm not sure.

**Comment by bspeare** [comment]
I'll take a closer look at it when I fix #168.
