### ISSUE TITLE
Move default block visibility settings from uiowa_lb_blocks to entity_types

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa01#137]
- Add as a function in entity_types.module

**Comment by pyrello** [comment]
I have been search for `hook_*` functions and entity type events that I could use to attach this code to. Saving the manage display form and changing whether layout builder is used for a content type doesn't appear to trigger the `EventTypes::UPDATE` event to be dispatched. Moreover, there is not a comparable `hook_entity_type_update()` event - just `hook_entity_type_create()` and `hook_entity_type_delete()`.

So, my approach at this point is to do the following:
* Add `hook_install()` and `hook_uninstall()` functions to each `entity_types_*` content type module's `.install` file.
* Add a hook_form_FORM_ID_alter function that is triggered when the entity manage display form is saved and add a submit handler.
* Create a submit handler function that checks what the layout builder setting has been saved to and changes the block visibility setting accordingly.

These cases handle module install and uninstall, as well as manually updating the setting. Does that cover all cases you can think of @bspeare and @mark-bennett-uiowa?

**Comment by mark-bennett-uiowa** [comment]
For the most part, yes, I believe you're correct above. I can think more about this after I finish current project.

**Comment by pyrello** [comment]
This is a little bit trickier than it first seems. When you unselect "Use Layout Builder" and submit the manage display form, it takes you to confirmation page, which uses a different form. Since it is possible to unselect that option, then click the cancel button on the confirmation page, you can't set the visibility values based on the manage display form being submitted when layout builder $enabled = 0. The secondary form doesn't seem to contain any reference to the entity type in question, so the logic I wrote doesn't work on that form.

**Comment by pyrello** [comment]
I have run into another issue that I had previously not thought of:

If you manually enable layout builder and this code runs which sets the block visibility settings to hide the title and breadcrumb blocks, but the entity type doesn't have a layout template including the title and breadcrumb, then they just disappear on the relevant pages. They can be re-added to the layout template for that entity type, but that also has to be done manually.

This makes me wonder whether having this type of code run when making manual changes is actually a good idea. I could see maybe for disabling layout builder that it could make sense. You are removing the layout template from being in play. You don't want to then have the page title and breadcrumbs not show up on content pages after its been disabled.

So, I think maybe we should just have this run on disabling layout builder templates. If you manually choose to enable layout builder, you are responsible for both setting the block visibility settings and adding the page title and breadcrumbs to the layout template for that content type.

Make sense? Sound like a good plan?

**Comment by pyrello** [comment]
It seems that hook_install isn't able to act on blocks being enabled during a site install because there appears to be no blocks enabled at that point. I'm going to try out this patch to see if it gives me the functionality I am seeking.

**Comment by pyrello** [comment]
Future work in this area will be based on #174
