### ISSUE TITLE
How to handle custom block types with multiple compound fields?

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#14]
This has been an ongoing question that we have yet to figure out the answer for. Essentially, it boils down to having a custom block type to place an element like a carousel on a page. The carousel is made up of multiple items that each have multiple fields, such as headline, image, link.

Last I checked, when this type of custom block is created, the layout builder inline block revisioning system doesn't handle revisions correctly for the nested fields.

This issue is a place to track where we are at with solving this issue, what we have tried, and any ideas we might have.

**Comment by pyrello** [comment]
Here are some notes from a recent conversation on Slack:

> Sean [2:21 PM]
Hello. I'm wondering how people are handling creating a custom block type that is a container for multiple individual items? For example, a slideshow custom block type, where you can add multiple individual slides. Since each slide is going to consist of a title, image, description, and link, then each slide is itself a block type item. I have a need to be able to create a lot of these types of nested compound block types and I don't have a good idea of how to do it

>bkosborne [2:34 PM]
block with paragraphs field is one option
for “slideshow” we use a media type for that
and then have a block that allows placing the slideshow

>Sean [3:48 PM]
@bkosborne Have you tried the block with paragraphs field option? The last time I tried that, it did not appear to work correctly with revisions in the context of a layout page.
For your slideshow media type, would you care to share how that is structured?

>bkosborne [3:50 PM]
I haven’t tries blocks with paragraphs
Slideshow media type is just a media bundle with “media entity slideshow” plugin (tiny contrib module)
There’s a multi value entity reference field to Image media bundle

>Sean [3:52 PM]
Gotcha. So the title and description fields would be attached to the Image media bundle
Thanks for the ideas.
I guess I’m looking for something a little more generic than that, though. A few other examples would be accordions and tabs, both of which similarly have a container type around referenced item types. Paragraphs handles this type of thing pretty well, but doesn’t play nice with layout yet, that I am aware of

>dsquaredb [3:57 PM]
we create a block that is a container block and then add individual blocks to that block container.

>Sean [4:00 PM]
@dsquaredb So, you have a container block type and individual item block type and the container type contains an entity reference revisions field to the individual item block type?
Roughly speaking

>dsquaredb [4:00 PM]
yes
so, for instance, we create a card block that has a title, subtitle, image, link
then we create a Multi Cards block that has a reference to Card Block
and we have themed that to be a slideshow or a grid layout, etc.

>Sean [4:02 PM]
Interesting. Do you have to finesse it with layouts, or does it work pretty well?

>dsquaredb [4:02 PM]
It’s worked well so far

>Sean [4:02 PM]
All right then. I’ll give that a shot
Thanks for the tip

**Comment by pyrello** [comment]
It also looks like Paragraphs has made some progress with being able to handle revisioning which might impact this as well: https://www.drupal.org/project/paragraphs/releases/8.x-1.7

**Comment by pyrello** [comment]
In our meeting yesterday, I proposed a scenario that might be able to make this work (using the example scenario of a Slideshow with child Slides):

A slideshow custom block type that has no fields and is set up (under manage display) to give control over its display to Layout Builder. A separate slide custom block type is also created with label, caption, and image fields. Using the Layout Builder Restrictions module, the Slideshow block type is limited to only the one column layout and is only allowed to use blocks of the Slide type for placement via Layout Builder.

I put together a test site with this configuration and it does not work as expected. Layout Builder does not seem to have a way to handle nested entities that enable Layout Builder also.

I'm looking into possible ways that I could make this work via the lb_enhancements custom module that I'm working on in uiowa/uiowa01#79

**Comment by bspeare** [comment]
Adding the responses from Slack from yesterday:

> mandclu Yesterday at 11:22 AM
> To me it would make more sense to make a custom section called “Accordions” and any block you put in there is formatted as a details element, with the block title as the summary

> Sean  1 day ago
> What if you also wanted to put 2 accordions side-by-side?

> mandclu  1 day ago
> If you wanted to allow for that, you could still have columns, and have the blocks within the columns render as accordions

**Comment by bspeare** [comment]
@pyrello what do you see as the drawbacks for using custom sections dedicated to 'Accordions', or 'Banner', or 'Slideshow'?  Creating a container block within a section seems a bit excessive since the functionality is already possible through custom layouts.

**Comment by pyrello** [comment]
@bspeare I think that from a standpoint of likely use cases, we have come up with a sufficient solution by creating sections for Banner, Slideshow, Accordions, etc. My only qualm with it is about the fact that it is not ultimately as flexible as I think it should be. In looking into what it would take to create a layout within a layout UI implementation, there are some pretty serious changes to core pieces that would need to change to allow it to happen without creating a bunch of duplicated code in different places. I think the level of effort required is not worth it, at least at this point. I have followed a number of issues on Drupal.org that seem to be at least partially related and intend to follow this issue as it moves forward within the community. But for the time being, I think that we have our solution.

**Comment by pyrello** [comment]
Here are a few of the related issues I have found:
* https://www.drupal.org/project/drupal/issues/3053145
* https://www.drupal.org/project/drupal/issues/3075939
* https://www.drupal.org/project/drupal/issues/3028391

**Comment by pyrello** [comment]
I think I'll close this issue for now and we can re-open if we need to revisit the issue.
