### ISSUE TITLE
Add iowasuperfund.uiowa.edu

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#146]
# Content types
- [x] Basic page - provided by entity_types_page module
- [x] News item - provided by entity_types_news module
- [ ] Person (Personnel) - provided by entity_types_people module?

# Content fragments
- [ ] Homepage slider - block type?
- [ ] Publication

# Views
- [ ] News and events - https://iowasuperfund.uiowa.edu/news-and-events
- [ ] Homepage slider
- [ ] Synthesis core highlights list => convert to menu
- [ ] Personnel list - doesn't exist in current site

# Blocks
- [ ] Program and Research Support Cores

# Migrations
- [ ] News item

**Comment by pyrello** [comment]
# Person content type
- First name
- Last name
- Organization
- Email
- Title (textarea - HTML)
- Image

**Comment by mark-bennett-uiowa** [comment]
Can you still use the entity_types module and just not use the additional fields? Not sure you really need to create another person type. The point of the modules are to provide functionality for most of the sites. Once we start getting into creating new modules for stripped down or higher need sites, we end up where we are now.

**Comment by pyrello** [comment]
Are you suggesting that I have the extra fields and just not use them? Or that I install as is and then remove the fields from the site prior to creating the content?

**Comment by mark-bennett-uiowa** [comment]
Im suggesting the former; use the module as is, and just leave content out of the additional (unnecessary) fields. It may reach a point later where the site will need to use them, or it can be presented to the site owners that they have additional fields they can use for people pages.

**Comment by pyrello** [comment]
Continued in #159
