### ISSUE TITLE
Use blocks instead of paragraphs?

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#15]
Note: This issue will eventually live in the repo for the uiowa_sections module, but is going to live here until that is created.

This is a place to keep track of any discussion/notes/resources around deciding whether to go with a paragraphs-type approach similar to what the sitenow profile uses, or to possibly use custom blocks + block fields + layout builder to accomplish something similar.

Here's is what I understand so far:
* Using Entity References (and I'm assuming possibly Entity Reference Revisions) fields, you can reference plugin blocks (config) or custom blocks (content) but not both with the same field.
* There is a field that supersedes the blockreference module called block_field, which I am going to test out.
* Custom blocks have some sort of revisioning in place or in progress, but no UI exists for it yet. The block revisions are supposed to be an 8.7 feature and the UI to support them is possibly an 8.8 feature.
* The layout builder module has some way of working with custom blocks that needs some additional investigation. I'm not sure if it include revisions or not.

Based on the above, it seems that if the block_field module doesn't provide a solution which provides revisions based on parent entity updates, then this may be a non-starter.

**Comment by bspeare** [comment]
Layout Builder Resources

-   Useful contrib modules for working with Layout Builder
    -   <https://www.drupal.org/project/layout_builder_restrictions>
    -   <https://www.drupal.org/project/block_blacklist>
    -   <https://www.drupal.org/project/layout_builder_styles> allow you to add classes to sections and blocks on layout builder for easier theming
    -   <https://www.drupal.org/project/layouts>
    -   <https://www.drupal.org/project/layout_builder_modal>
    -   <https://www.drupal.org/docs/8/core/modules/layout-builder/additional-modules>
    -   <https://www.drupal.org/project/layout_builder_enhancements>
    -   <https://www.drupal.org/project/layout_builder_styles>
    -   <https://www.drupal.org/docs/8/modules/layout-builder-styles>
    -   <https://discuss.pantheon.io/t/what-are-must-cover-topics-related-to-drupal-8s-layout-builder-feature/468/2>

**Comment by pyrello** [comment]
I tested a scenario using Layout Builder and custom block types. I created an Item custom block type (Title, Description), and a Container custom Block type (Items via entity reference). I set up a content type that could use per-node layout editing and then added a Container to my layout. I created the Item blocks via Inline Entity Form in a modal pop-up.

All the revisioning stuff seemed to work as expected. When I edited one of my Items, a revision was added to the parent node.

I noticed that the Item blocks I created, within the context of the node layout, showed up on the Custom block library page. That doesn't seem right. I haven't been able to figure out the exact reason from looking at the code, much of which is abstracted away by the Block Plugin system, but I think it is because the Item blocks are not direct children of the layout field on the node, they are not treated as inline blocks.

I'm not sure that this is a problem in that it is a deal-breaker as far as using blocks as our content fragment vehicle is concerned, but it makes me wonder if there are going to be other downstream effects of this. I think it could technically be considered a bug.

**Comment by bspeare** [comment]
Does this issue address what you noticed? 

https://www.drupal.org/project/drupal/issues/2957425

**Comment by pyrello** [comment]
I created an issue on Drupal.org: https://www.drupal.org/project/drupal/issues/3075925

**Comment by pyrello** [comment]
@bspeare It does not. I only skimmed a little bit of the discussion in that issue, but it appears to be the issue from which came the "Create custom block" link. That is what I used to create the container block. However, creating the nested blocks happens via an entity reference widget, such as IEF via Entity Browser.

**Comment by pyrello** [comment]
Using nested blocks referenced via the core entity_reference module does not allow for revision reversion to work correctly.

**Comment by pyrello** [comment]
Here are the scenarios that we are testing, so I can keep track:

|Test?|Container type|Item type|Reference type|Creation widget|Notes|
|:---:|---|---|---|---|---|
|Y|Block|Block|Entity Reference|Entity Browser + IEF|When reverting a revision, the nested block doesn't revert.|
|Y|Block|Block|Entity Reference Revisions|-|Unable to find a widget for creating nested block in place.|
|Y|Block|Paragraph|Entity Reference|Paragraphs widget|-|
|N|Block|Paragraph|Entity Reference Revisions|Paragraphs widget|-|
|N|Paragraph|Paragraph|Entity Reference Revisions|Paragraphs widget|-|

**Comment by pyrello** [comment]
Connecting to new issue for LB enhancements: #79

**Comment by pyrello** [comment]
I think we largely have this issue figured out. It seems we have use cases for using both paragraphs (compound fields as structured data on entities) and blocks (as entity fragments that can be placed via layout builder. I'm going to close this issue for now. Feel free to reopen if you think we need to revisit any parts of this discussion.
