### ISSUE TITLE
Fix column spacing for layouts in collegiate_theme

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa01#156]

**Comment by pyrello** [comment]
In the case of a 2-column layout, you have set margins on the inside of the blocks where they meet. In the case of a 3-column layout, the middle block sets the margin for all 3. I'm just wondering why the difference in approach for those?

**Comment by bspeare** [comment]
Which approach would you prefer?

**Comment by pyrello** [comment]
Having half the margin for the gutter live with each block makes the most sense to me. So, the 2-column approach.
