### ISSUE TITLE
Basic person content type

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#159]
The iowasuperfund.uiowa.edu site is going to require a person content type that is quite a bit stripped down from the version that is included with the entity_types version. I'm thinking that it might just make the most sense to just create a separate module for a person content type that is more limited for use cases similar to this. @mark-bennett-uiowa I would welcome any feedback you have on this idea, since you are our content type expert.

This is the proposed entity definition (Originally documented here: https://github.com/uiowa/uiowa01/issues/146#issuecomment-542055453):
# Person content type
- First name
- Last name
- Organization
- Email
- Title (textarea - HTML)
- Image

Related to #146

**Comment by pyrello** [comment]
Continuing the conversation from https://github.com/uiowa/uiowa01/issues/146#issuecomment-543257284

@mark-bennett-uiowa I'm not a big fan of the idea of leaving additional fields that are unneeded. I think that makes the UI more confusing for the person managing the site and increases the chances that records will be filled in inconsistently. It would be my preference for every site to make sure that only the fields that are needed/desired are included for each content type.

My thinking on this is that I am likely to have multiple sites where I have a person content type that requires a more minimal number of fields. My options would be to either create a new module for creating a basic person type, or using the existing module and removing the fields that I don't need. In the event that I need more fields than, I would add them manually unless it seemed likely the fields would be used by multiple sites.

Either way, I'm adding or subtracting fields.

**Comment by mark-bennett-uiowa** [comment]
@pyrello Are we good on this then? If you may be adding or subtracting fields, are we at an acceptable "middle-ground" that would work for your sites too?
