### ISSUE TITLE
Re-name collegiate_theme_base to something less confusing

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#16]
The name of the collegiate base theme has created issues. We need to change it to something that will cause less confusion.

**Comment by bspeare** [comment]
What do we want to name it?  I know we talked about collegiate_base but perhaps collegiate_theme will work better for setting up the subtheme template?

- collegiate_theme
- collegiate_subtheme

**Comment by pyrello** [comment]
I'm cool with collegiate_theme.
