### ISSUE TITLE
Adjust Slogan in Basic Site Settings to appear above or below Site Name.

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa01#184]
# The Problem 

Allow the Site Slogan to appear above or below the site name.

# Proposed Solution

Adjust or alter the settings on admin/config/system/site-information to determine the placement of the Site Slogan in the theme.

**Comment by bspeare** [comment]
How do we want to implement this?  Create a subtheme of Adminimal with `hook_form_FORM_ID_alter`?  Or a custom module that will add the settings no matter what admin theme is used?

**Comment by pyrello** [comment]
One option would be to add a theme setting, since the actual placement of the slogan would take place in the theme. That is the approach that makes the most sense to me at this point.

**Comment by bspeare** [comment]
That seems like a good option.   @mark-bennett-uiowa what do you think?
