### ISSUE TITLE
Verify whether page title and breadcrumbs should appear by default when using Entity Types News

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa01#186]
# Problem

When creating a new "Entity Types News" item, the page title and breadcrumbs will only appear if you go to admin/structure/block and edit/save the page title or breadcrumbs block.   Is this the correct functionality that we wanted from #137?

# Possible Solution

Allow breadcrumbs and page title to appear by default after creating a new "Entity Types News" item.

**Comment by pyrello** [comment]
Closed by #264
