### ISSUE TITLE
Choose one inline block text area solution for layout builder

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa01#189]
# The Problem 

There are currently two inline block text area options.   There is the "Basic Block" from core and "UIowa Text Area" block from the uiowa_lb_blocks module.  

# Proposed Solution

Delete one of the options from our solution.   Any preference?

**Comment by mark-bennett-uiowa** [comment]
I would vote for whatever naming convention we were going with. If that is the only type of "basic" text block we have, keep it named "Basic Block". If we have a "Text Field Block", a "Text Area Block", and a "Select List Block" (for example), name it "Text Area Block". If this is part of some big UIowa set of blocks, then name it that.
