### ISSUE TITLE
Add styling to collegiate_theme to make media_library modal look prettier

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#205]
# The Problem
When viewing the media_library widget for a media field via the modal popup from LB, it looks kind of messed up. I'm assuming this is because we don't provide any styling for it via collegiate_theme.

<img width="1068" alt="Screen Shot 2019-11-14 at 6 54 50 AM" src="https://user-images.githubusercontent.com/709009/68858916-c1decd80-06ab-11ea-829e-af4c7230e3d2.png">

# The Solution
Add styling to collegiate_theme to make media_library look nicer when accessed via the frontend.

**Comment by bspeare** [comment]
This is a noted issue in core with some suggested solutions: https://www.drupal.org/project/drupal/issues/3050508.

**Comment by pyrello** [comment]
Maybe we can fix this in the 8.8.x branch. I'll give it a test.

**Comment by mark-bennett-uiowa** [comment]
I can confirm that this is fixed in #214. Can close issue on merge.
