### ISSUE TITLE
"site-name" directory does not exist

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#21]
```console
The "themes/custom/collegiate_theme/node_modules/@bspeare/uds/components/site-name" directory does not exist ("/var/www/uiowa01/docroot/themes/custom/collegiate_theme/node_modules/@bspeare/uds/components/site-name").
```
When attempting to enable collegiate_theme website (using `drush then collegiate_theme`), I get the above error.

@bspeare Any ideas why this would be happening?

**Comment by bspeare** [comment]
Is the components module enabled?

**Comment by pyrello** [comment]
It is. I commented out the `collegiate_theme` entry on the collegiate_basic.info.yml file to ensure that it wasn't being installed and then ran `drush pml` to see what modules are installed.

With that line not commented out, the collegiate_theme is enabled on install and then running any drush command results in the originally reported error.

**Comment by pyrello** [comment]
This may have been because I didn't run `blt sbf`. I'm trying that now.

**Comment by pyrello** [comment]
Okay. That fixed it locally. This is still an issue on the Acquia Cloud side as it appears to be failing to include the node_modules folder in the build artifact. I think I'll leave this issue open until we get resolution on that.

**Comment by pyrello** [comment]
After following up on my hunch that this is because of the build process removing the `node_modules` folder, I have confirmed that this is the case. While it is possible to define our own exclude list, that means we are responsible for periodically comparing it to the original -  https://github.com/acquia/blt/blob/10.x/scripts/blt/deploy/deploy-exclude.txt - and keeping it up-to-date.

This reinforces the need to figure out how to have collegiate_theme built in such a way where it is not calling a file inside the node_modules file at all.

**Comment by pyrello** [comment]
I think that this issue is resolved now.
