### ISSUE TITLE
Adding block with form breaks LB saving on second save

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa01#217]
While editing an existing page with a custom layout, I am unable to save after updating the layout and adding new content.

1. Create a new basic page and add it as frontpage content.
2. Edit the layout for just that page (not all instances of that content type).
3. Add a new section with the Collegiate three column layout (33/34/33).
4. Insert one UIowa Card item into each of the three columns.
5. Save the changes to close the LB interface.
6. Return to the page, and repeat steps 3 - 4 above directly below the previously created section.
7. Attempt to save the new changes.

When trying to save these new changes, the save may fail and show the following:
![Screen Shot 2019-11-18 at 1 20 52 PM](https://user-images.githubusercontent.com/3067017/69084224-65f8a980-0a09-11ea-8e82-0d41c46f2957.png)

**Comment by mark-bennett-uiowa** [comment]
I just deleted the page and recreated it without any errors. Trying to recreate the errors as I type.

**Comment by mark-bennett-uiowa** [comment]
Edited the page again after saving initial changes. Added a feature above a banner in a separate section and the same issue above occurred.

**Comment by mark-bennett-uiowa** [comment]
This seems to be resolved in the latest pull. Closing.

**Comment by mark-bennett-uiowa** [comment]
Still an issue.

**Comment by mark-bennett-uiowa** [comment]
This is still appearing now and it appears to happen when I added a Banner and a Feature to the same section. Both have Full Width Container style.

**Comment by bspeare** [comment]
@mark-bennett-uiowa Have you tried running a site install and then a `drush cr` and then following your steps?  If so, does the error still happen?

**Comment by mark-bennett-uiowa** [comment]
@bspeare I have tried running a site install, adding components, and using drush cr after that point.  It still leads to a "crash" unfortunately. I havent run drush cr immediately after a site install however.

**Comment by pyrello** [comment]
@mark-bennett-uiowa Is this still an issue after the update to 8.8.x? I can't remember if you had already tested that.

**Comment by mark-bennett-uiowa** [comment]
@pyrello Yes its still an issue unfortunately.

**Comment by bspeare** [comment]
I'm noticing Mark's error on https://simplytest.me/.   

1. Run 8.8 rc
2. Install layout builder
3. Enable layout builder for basic page
4. Add search form to a two-column layout
5. Save the page
6. Edit the page and move the search form to the second column
7. Try saving the page

Possible issue: https://www.drupal.org/project/drupal/issues/3065003

**Comment by bspeare** [comment]
Patch is available on this issue: https://www.drupal.org/project/drupal/issues/3045171

**Comment by pyrello** [comment]
I tested this patch and it did not appear to work.

**Comment by bspeare** [comment]
Which one did you try?  There are so many!   This one?  

https://www.drupal.org/project/drupal/issues/3045171#comment-13405560

**Comment by pyrello** [comment]
Yes, that is the one. That one incorporates recommendations from https://www.drupal.org/project/drupal/issues/3045171#comment-13405166 that applied to the patch in https://www.drupal.org/project/drupal/issues/3045171#comment-13403665, which in turn corrected a spelling error in https://www.drupal.org/project/drupal/issues/3045171#comment-13357205. People reported that that first patch worked. We could try the rest of them. I could also try to figure out why the patch isn't working.

**Comment by pyrello** [comment]
It might be a good idea to try testing it again. I did do a fresh install after applying the patch, but there may have been something going on in my local environment that I wasn't aware of.

**Comment by bspeare** [comment]
@pyrello Let me give the patch a try first before you spend any more time on it.

**Comment by pyrello** [comment]
@bspeare Sounds good. Let me know what you encounter.

**Comment by bspeare** [comment]
@pyrello I just used this patch and it worked: https://www.drupal.org/files/issues/2019-12-28/layout-builder-save-issue-3045171-120.patch

**Comment by pyrello** [comment]
Want to push your work as a new feature branch?

**Comment by bspeare** [comment]
@pyrello close or transfer this one?

**Comment by pyrello** [comment]
I think this can be closed in favor of #318
