### ISSUE TITLE
Three versions of Media tab (2 not working) under Content

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa01#220]
<img width="513" alt="Screen Shot 2019-11-19 at 2 08 45 PM" src="https://user-images.githubusercontent.com/3067017/69182192-2350d300-0ad6-11ea-916b-5182cc8c5edd.png">

**Comment by pyrello** [comment]
This is not happening for me in the feature_drupal_8_8_x branch, so maybe it is fixed there?

**Comment by mark-bennett-uiowa** [comment]
I can confirm that this is fixed in the 8.8.x branch. Since that PR was merged with master, we can close this issue.
