### ISSUE TITLE
Rename uds inside collegiate_theme to use uiowa/hds repo

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa01#26]
This will depend on whether the "project site" version of https://pages.github.com/ will work for hosting the static fractal build of the component library.

**Comment by bspeare** [comment]
I also added "hds" folder to the .gitignore.   Do we need to commit this folder since it is being generated with `blt sbf`?

**Comment by pyrello** [comment]
I believe that the "hds" folder should be committed. It is added via the `gulp copy` or `npm run copy` commands, which is just part of the process workflow for the theme. I don't believe that is something that runs during `blt sbf`. Also, the plan is to remove the `frontend:*` commands from the build process in the near future, as adding the "hds" folder means we don't need them anymore.
