### ISSUE TITLE
Investigate smart_date module as a solution for date/time entry woes

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#283]
@mark-bennett-uiowa Am I crazy or did we talk about using this module before? I can't find any record of the conversation on here, so maybe it was via slack?

Anyways, I was just reading an [article](https://internetdevels.com/blog/event-schedules-smart-date-drupal-module) about the smart_date module (https://www.drupal.org/project/smart_date) and I think that it potentially resolves some of the issues we have with how the date/time entry is funky by default.

If there isn't a compelling reason why @mark-bennett-uiowa decided not to use this module already, I think we should incorporate it and update our date fields to use it.

**Comment by pyrello** [comment]
Related to #261

**Comment by pyrello** [comment]
I decided to check this out. I like some aspects of the smart_date module:
* It toggles the display of the end date if the "all day" checkbox is clicked
* It keeps the end date and time in sync with the start date and time - that is, it makes sure that the end date and time is not before the start date and time
* It allows for very specific durations to be created, which could be nice for certain sites
* It stores the dates in a format that is more performant than the core date field

However, it has some flaws:
* At this point, is that it seems to depend on the idea of the duration being there regardless of whether or not you want to use it. The duration increments field as well as the default duration field are both required. And the duration field displays even if there is only one option, which doesn't make any sense to me.
* It also doesn't allow you to make time completely optional
* Also, rather than solve the issue of allowing seconds to be toggled on or off from display, they are just hidden entirely

My feeling after looking at this is that it contains some good ideas but isn't quite there in terms of what we are looking for.

**Comment by mark-bennett-uiowa** [comment]
I also vote to wait. I really like this module, and think long term this is the way to go. However, until they fix some of these issues, I think we should wait.

**Comment by pyrello** [comment]
The other issue with smart_date is that, because it creates its own field type, which could make it problematic down the road to switch over to something more standardized.
