### ISSUE TITLE
Update collegiate_theme so that the copy function runs with gulp watch

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa01#29]
In testing the new collegiate_theme it doesn't seem like the new gulp copy function is running.   How were you running this function in the gulp.js file @pyrello?

**Comment by bspeare** [comment]
It looks like you are running it with `blt sbf` - is that correct?  If that's the case, then I can close this issue.

**Comment by pyrello** [comment]
I was running it with `npm run copy`. I didn't add it to the watch command because it really only needs to be run once when the npm package for UDS is updated. At that point, all the files get copied over and then don't change until the npm package is updated again.

**Comment by bspeare** [comment]
Thanks, I'll just adjust it locally.
