### ISSUE TITLE
SAML authentication issue after logging into Production site.

### ISSUE THREAD

**Issue by mark-bennett-uiowa** [uiowa/uiowa01#290]
I just encountered an issue while logging into a production site using my HawkID rather than an admin uli command.
`Error encountered while processing SAML authentication response; details have been logged.`

![Screen Shot 2019-12-20 at 2 01 56 PM](https://user-images.githubusercontent.com/3067017/71288879-5682be00-2331-11ea-81b1-d589a264a89a.png)

**Comment by mark-bennett-uiowa** [comment]
Here is the error log from Reports:
Location: https://policy.clas.uiowa.edu/saml/acs
Referrer: https://idp.uiowa.edu/idp/profile/SAML2/Redirect/SSO?execution=e1s3
Message: Exception encountered while processing SAML authentication response: Configured unique ID is not present in SAML response. in Drupal\samlauth\SamlService->acs() (line 185 of /mnt/www/html/uiowa01/docroot/modules/contrib/samlauth/src/SamlService.php).

**Comment by mark-bennett-uiowa** [comment]
I just checked out the SAML Authentication admin section and it looks like we have nothing stored in these fields as far as Identity Provider Configuration and User Info and Syncing. Shouldnt we have something in these fields for the site to connect properly?
![Screen Shot 2019-12-20 at 4 20 45 PM](https://user-images.githubusercontent.com/3067017/71296340-d5cdbd00-2344-11ea-98b2-6c537f0f24f5.png)

**Comment by richardbporter** [comment]
The module readme describes why some of those are blank: https://github.com/uiowa/uiowa_auth/blob/master/README.md

________________________________

**Comment by pyrello** [comment]
I think he got this figured out. I gave him access to the cogscilang site so he could use that as a reference.

**Comment by richardbporter** [comment]
Ok good. 👍

________________________________

**Comment by mark-bennett-uiowa** [comment]
Yes, this is now solved. Thanks guys! Were these settings able to be added to the profiles for installation during setup?

**Comment by pyrello** [comment]
@mark-bennett-uiowa Yes, in #303 (closing #302)
