### ISSUE TITLE
How to update collegiate profile within uiowa01

### ISSUE THREAD

**Issue by bspeare** [uiowa/uiowa01#32]
I just did a new `git clone` of uiowa01 and then `composer install` and it is installing a version of the collegiate profile in docroot/profiles/contrib/collegiate that still has the collegiate.info.yml file from around Mar 27, 2019 before it was updated to include the Lightning parts.    @pyrello can you remind me what step I'm missing to get the right profile working in uiowa01?

**Comment by pyrello** [comment]
To update the commit reference to collegiate in this repo:
1. Make sure you are on the master branch and it is up-to-date.
2. Update `uiowa/collegiate` via composer:
    `composer update uiowa/collegiate`
3. Commit and push.

Then, if you have multiple instance of this repo checked out, you'll need to:
1. `git checkout master && git pull`
2. `composer install`

**Comment by bspeare** [comment]
Thanks for the reminder!
