### ISSUE TITLE
Add grad.uiowa.edu

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#51]

**Comment by pyrello** [comment]
@richardbporter @joewhitsitt I'm curious to get your input about tickets like this. It looks like you have tickets for most/all of the sites your provision. I think we probably want to do the same thing.

**Comment by joewhitsitt** [comment]
So we have a site request form now where we track site requests (add notes, communicate with customer) and I don't think we are creating issues for each new site. Sometimes our PRs include multiple sites in one go. Instead, if there are special tasks with the site (needs SSL cert), we have been creating issues for those. You are free to do what you want but it ends up being one more thing for us.

**Comment by richardbporter** [comment]
Yea, I don't think we have tickets for every site provision/deprovision. Probably just ones that we want to assign to someone else to be done at a later time.

**Comment by pyrello** [comment]
Okay. Thanks for your input.
